# Generated by Django 6.0 on 2025-12-14 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the sweet (max 200 characters).', max_length=200, verbose_name='sweet name')),
                ('description', models.TextField(blank=True, help_text='Optional description of the sweet.', verbose_name='description')),
                ('category', models.CharField(choices=[('chocolate', 'Chocolate'), ('candy', 'Candy'), ('cake', 'Cake'), ('cookie', 'Cookie'), ('dessert', 'Dessert'), ('indian', 'Indian Sweet'), ('bakery', 'Bakery Item'), ('other', 'Other')], default='other', help_text='Select the category of the sweet.', max_length=50, verbose_name='category')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit in INR.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='price')),
                ('quantity', models.IntegerField(default=0, help_text='Number of units available in stock.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantity in stock')),
                ('image', models.ImageField(blank=True, help_text='Optional image of the sweet.', null=True, upload_to='sweet_images/', verbose_name='sweet image')),
                ('calories', models.PositiveIntegerField(blank=True, help_text='Calories per serving (optional).', null=True, verbose_name='calories')),
                ('is_featured', models.BooleanField(default=False, help_text='Check to feature this sweet on the homepage.', verbose_name='featured item')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'sweet',
                'verbose_name_plural': 'sweets',
                'ordering': ['-created_at', 'name'],
                'indexes': [models.Index(fields=['name'], name='api_sweet_name_1c5f47_idx'), models.Index(fields=['category'], name='api_sweet_categor_02c295_idx'), models.Index(fields=['price'], name='api_sweet_price_ab2afe_idx'), models.Index(fields=['created_at'], name='api_sweet_created_beca83_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='price_positive'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='quantity_non_negative')],
            },
        ),
    ]
